name: docker tag name
description: Calculate parameters for tagging a docker image
inputs:
  project:
    description: name of project and docker repo
    required: true
  task:
    description: either "prepare" or "push"
    default: "prepare"
    required: true  
  registry:
    description: host for registry. required only for push.
    required: false
  username:
    description: username for registry. required only for push.
    required: false
  password:
    description: password for registry. required only for push.
    required: false

outputs:
  docker_branch_name:
    description: shortened branch name used for tagging, e.g. just "master"
  docker_version:
    description: version string for tags, e.g. "master.e722b2"
  docker_tag:
    description: full tag, e.g. "repo/app:master.e722b2"
runs:
  using: node20
  main: index.js
