name: Build and test run the action
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          project: mindhaq/action-docker-tags
          task: prepare